// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io.hadrien.wire.TestGrpcService in test.proto
package io.hadrien.wire

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.GrpcStreamingCall

public class GrpcTestGrpcServiceClient(
  private val client: GrpcClient
) : TestGrpcServiceClient {
  public override fun Unary(): GrpcCall<Input, Output> = client.newCall(GrpcMethod(
      path = "/io.hadrien.wire.TestGrpcService/Unary",
      requestAdapter = Input.ADAPTER,
      responseAdapter = Output.ADAPTER
  ))

  public override fun Outbound(): GrpcStreamingCall<Input, Output> =
      client.newStreamingCall(GrpcMethod(
      path = "/io.hadrien.wire.TestGrpcService/Outbound",
      requestAdapter = Input.ADAPTER,
      responseAdapter = Output.ADAPTER
  ))

  public override fun Inbound(): GrpcStreamingCall<Input, Output> =
      client.newStreamingCall(GrpcMethod(
      path = "/io.hadrien.wire.TestGrpcService/Inbound",
      requestAdapter = Input.ADAPTER,
      responseAdapter = Output.ADAPTER
  ))

  public override fun InboundOutbound(): GrpcStreamingCall<Input, Output> =
      client.newStreamingCall(GrpcMethod(
      path = "/io.hadrien.wire.TestGrpcService/InboundOutbound",
      requestAdapter = Input.ADAPTER,
      responseAdapter = Output.ADAPTER
  ))
}
