// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io.hadrien.wire.TestGrpcService in test.proto
package io.hadrien.wire

import com.squareup.wire.Service
import com.squareup.wire.WireRpc
import kotlinx.coroutines.channels.ReceiveChannel
import kotlinx.coroutines.channels.SendChannel

public interface TestGrpcServiceServer : Service {
  @WireRpc(
    path = "/io.hadrien.wire.TestGrpcService/Unary",
    requestAdapter = "io.hadrien.wire.Input#ADAPTER",
    responseAdapter = "io.hadrien.wire.Output#ADAPTER"
  )
  public suspend fun Unary(request: Input): Output

  @WireRpc(
    path = "/io.hadrien.wire.TestGrpcService/Outbound",
    requestAdapter = "io.hadrien.wire.Input#ADAPTER",
    responseAdapter = "io.hadrien.wire.Output#ADAPTER"
  )
  public suspend fun Outbound(request: Input, response: SendChannel<Output>): Unit

  @WireRpc(
    path = "/io.hadrien.wire.TestGrpcService/Inbound",
    requestAdapter = "io.hadrien.wire.Input#ADAPTER",
    responseAdapter = "io.hadrien.wire.Output#ADAPTER"
  )
  public suspend fun Inbound(request: ReceiveChannel<Input>): Output

  @WireRpc(
    path = "/io.hadrien.wire.TestGrpcService/InboundOutbound",
    requestAdapter = "io.hadrien.wire.Input#ADAPTER",
    responseAdapter = "io.hadrien.wire.Output#ADAPTER"
  )
  public suspend fun InboundOutbound(request: ReceiveChannel<Input>, response: SendChannel<Output>):
      Unit
}
